import type { DocumentCategory, DocumentType } from '../../types';

export const foreignWorkersCategory: DocumentCategory = {
  id: 'foreign-workers',
  name: 'אישורי עובדים זרים',
  nameEnglish: 'Foreign Workers',
  description: 'אישורים למשרד הפנים - רשות האוכלוסין ההגירה ומעברי גבול',
  icon: 'Users',
  order: 1,
  permissions: {
    defaultRoles: ['admin', 'accountant', 'bookkeeper'],
    requiresOverride: true,
  },
  documentTypes: [
    'foreign-workers:accountant-turnover',
    'foreign-workers:israeli-workers',
    'foreign-workers:living-business',
    'foreign-workers:turnover-approval',
    'foreign-workers:salary-report',
  ],
};

export const foreignWorkersTypes: DocumentType[] = [
  {
    id: 'foreign-workers:accountant-turnover',
    categoryId: 'foreign-workers',
    name: 'דוח מחזורים רו"ח',
    nameEnglish: 'Accountant Turnover',
    description: 'דוח מחזורים חודשי - 12 חודשים',
    templatePath: 'foreign-workers/accountant-turnover.html',
    headerPath: 'components/foreign-workers-header.html',
    requiresClient: true,
    requiresBranch: true,
    requiresMonthlyData: true,
    variablesSchema: {
      shared: ['company_name', 'tax_id', 'document_date'],
      specific: [
        {
          key: 'monthly_turnover',
          label: 'נתוני מחזור חודשי',
          type: 'table',
          required: true,
          tableColumns: [
            { key: 'month', label: 'חודש', type: 'text', required: true },
            { key: 'turnover', label: 'מחזור', type: 'currency', required: true },
          ],
        },
      ],
    },
    formComponent: 'AccountantTurnoverForm',
    hasPaymentSection: false,
    order: 0,
  },
  {
    id: 'foreign-workers:israeli-workers',
    categoryId: 'foreign-workers',
    name: 'דוח עובדים ישראליים',
    nameEnglish: 'Israeli Workers',
    description: 'דוח מספר עובדים ישראליים לפי חודשים',
    templatePath: 'foreign-workers/israeli-workers.html',
    headerPath: 'components/foreign-workers-header.html',
    requiresClient: true,
    requiresBranch: true,
    requiresMonthlyData: true,
    variablesSchema: {
      shared: ['company_name', 'tax_id', 'document_date'],
      specific: [
        {
          key: 'monthly_workers',
          label: 'מספר עובדים חודשי',
          type: 'table',
          required: true,
          tableColumns: [
            { key: 'month', label: 'חודש', type: 'text', required: true },
            { key: 'workers_count', label: 'מספר עובדים', type: 'number', required: true },
          ],
        },
      ],
    },
    formComponent: 'IsraeliWorkersForm',
    hasPaymentSection: false,
    order: 1,
  },
  {
    id: 'foreign-workers:living-business',
    categoryId: 'foreign-workers',
    name: 'עסק חי',
    nameEnglish: 'Living Business',
    description: 'הצהרה על עסק פעיל עם מומחים זרים',
    templatePath: 'foreign-workers/living-business.html',
    headerPath: 'components/foreign-workers-header.html',
    requiresClient: true,
    requiresBranch: true,
    requiresMonthlyData: false,
    variablesSchema: {
      shared: ['company_name', 'tax_id', 'document_date'],
      specific: [
        {
          key: 'certificate_year',
          label: 'שנת אישור',
          type: 'number',
          required: true,
        },
        {
          key: 'foreign_experts_count',
          label: 'מספר מומחים זרים',
          type: 'number',
          required: true,
        },
      ],
    },
    formComponent: 'LivingBusinessForm',
    hasPaymentSection: false,
    order: 2,
  },
  {
    id: 'foreign-workers:turnover-approval',
    categoryId: 'foreign-workers',
    name: 'אישור מחזור/עלויות',
    nameEnglish: 'Turnover Approval',
    description: 'אישור מחזור ועלויות לפי תרחיש (12+, 4-11, עד 3 חודשים)',
    templatePath: 'foreign-workers/turnover-approval.html',
    headerPath: 'components/foreign-workers-header.html',
    requiresClient: true,
    requiresBranch: true,
    requiresMonthlyData: false,
    variablesSchema: {
      shared: ['company_name', 'tax_id', 'document_date'],
      specific: [
        {
          key: 'scenario',
          label: 'תרחיש',
          type: 'select',
          required: true,
          options: [
            { value: '12_plus', label: '12 חודשים ומעלה' },
            { value: '4_to_11', label: '4-11 חודשים' },
            { value: 'up_to_3', label: 'עד 3 חודשים' },
          ],
        },
        { key: 'period_start', label: 'תחילת תקופה', type: 'date', required: true },
        { key: 'period_end', label: 'סוף תקופה', type: 'date', required: false },
        { key: 'total_turnover', label: 'סה"כ מחזור', type: 'currency', required: false },
        { key: 'estimated_costs', label: 'עלויות משוערות', type: 'currency', required: false },
      ],
    },
    formComponent: 'TurnoverApprovalForm',
    hasPaymentSection: false,
    order: 3,
  },
  {
    id: 'foreign-workers:salary-report',
    categoryId: 'foreign-workers',
    name: 'דוח שכר',
    nameEnglish: 'Salary Report',
    description: 'טבלת שכר עובדים עם חתימות',
    templatePath: 'foreign-workers/salary-report.html',
    headerPath: 'components/foreign-workers-header.html',
    requiresClient: true,
    requiresBranch: true,
    requiresMonthlyData: false,
    variablesSchema: {
      shared: ['company_name', 'tax_id', 'document_date'],
      specific: [
        { key: 'period_start', label: 'תחילת תקופה', type: 'date', required: true },
        { key: 'period_end', label: 'סוף תקופה', type: 'date', required: true },
        {
          key: 'workers_data',
          label: 'נתוני עובדים',
          type: 'table',
          required: true,
          tableColumns: [
            { key: 'full_name', label: 'שם מלא', type: 'text', required: true },
            { key: 'passport_number', label: 'מספר דרכון', type: 'text', required: true },
            { key: 'report_month', label: 'חודש דיווח', type: 'text', required: true },
            { key: 'nationality', label: 'לאום', type: 'text', required: true },
            { key: 'salary', label: 'שכר בסיס', type: 'currency', required: true },
            { key: 'supplement', label: 'תוספת', type: 'currency', required: false },
          ],
        },
        { key: 'senior_manager_signature', label: 'חתימת מנהל בכיר', type: 'signature', required: true },
        { key: 'finance_manager_signature', label: 'חתימת מנהל כספים', type: 'signature', required: true },
        { key: 'company_stamp', label: 'חותמת חברה', type: 'signature', required: false },
      ],
    },
    formComponent: 'SalaryReportForm',
    hasPaymentSection: false,
    order: 4,
  },
];
