// Database types generated from Supabase schema
// This file will be auto-generated by Supabase CLI in production

export type UserRole = 'admin' | 'accountant' | 'bookkeeper' | 'client';
export type TenantType = 'internal' | 'white_label';
export type TenantStatus = 'active' | 'inactive' | 'trial' | 'suspended';
export type FeeStatus = 'draft' | 'sent' | 'paid' | 'overdue' | 'cancelled';
export type PaymentStatus = 'pending' | 'completed' | 'failed' | 'refunded';
export type LetterTemplateType = 
  | 'annual_fee_notification'
  | 'fee_increase_inflation'
  | 'fee_increase_real'
  | 'payment_reminder_gentle'
  | 'payment_reminder_firm'
  | 'payment_overdue'
  | 'service_suspension_warning'
  | 'payment_confirmation'
  | 'new_client_welcome'
  | 'service_completion'
  | 'custom_consultation';

export interface Database {
  public: {
    Tables: {
      tenants: {
        Row: {
          id: string;
          name: string;
          type: TenantType;
          status: TenantStatus;
          subscription_plan: string | null;
          custom_domain: string | null;
          theme_config: Record<string, unknown>;
          settings: Record<string, unknown>;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['tenants']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['tenants']['Insert']>;
      };
      tenant_users: {
        Row: {
          id: string;
          tenant_id: string;
          user_id: string;
          role: UserRole;
          permissions: Record<string, unknown>;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['tenant_users']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['tenant_users']['Insert']>;
      };
      clients: {
        Row: {
          id: string;
          tenant_id: string;
          company_name: string;
          company_name_hebrew: string | null;
          tax_id: string;
          contact_name: string;
          contact_email: string | null;
          contact_phone: string | null;
          contact_address: string | null;
          contact_city: string | null;
          status: 'active' | 'inactive' | 'pending';
          group_id: string | null;
          notes: string | null;
          custom_fields: Record<string, unknown>;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['clients']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['clients']['Insert']>;
      };
      fee_types: {
        Row: {
          id: string;
          tenant_id: string;
          name: string;
          description: string | null;
          default_amount: number | null;
          is_active: boolean;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['fee_types']['Row'], 'id' | 'created_at'>;
        Update: Partial<Database['public']['Tables']['fee_types']['Insert']>;
      };
      fee_calculations: {
        Row: {
          id: string;
          tenant_id: string;
          client_id: string;
          year: number;
          month: number | null;
          fee_type_id: string | null;
          base_amount: number;
          inflation_adjustment: number;
          custom_adjustment: number;
          discount_amount: number;
          final_amount: number;
          status: FeeStatus;
          notes: string | null;
          payment_date: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: Omit<Database['public']['Tables']['fee_calculations']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['fee_calculations']['Insert']>;
      };
      letter_templates: {
        Row: {
          id: string;
          tenant_id: string;
          template_type: LetterTemplateType;
          name: string;
          language: 'he' | 'en';
          subject: string | null;
          content_html: string;
          content_text: string | null;
          variables_schema: Record<string, unknown>;
          selection_rules: Record<string, unknown> | null;
          is_active: boolean;
          version: number;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['letter_templates']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['letter_templates']['Insert']>;
      };
      generated_letters: {
        Row: {
          id: string;
          tenant_id: string;
          client_id: string;
          template_id: string;
          fee_calculation_id: string | null;
          variables_used: Record<string, unknown>;
          generated_content_html: string;
          generated_content_text: string | null;
          payment_link: string | null;
          sent_at: string | null;
          sent_via: string | null;
          opened_at: string | null;
          clicked_at: string | null;
          created_at: string;
          created_by: string | null;
        };
        Insert: Omit<Database['public']['Tables']['generated_letters']['Row'], 'id' | 'created_at'>;
        Update: Partial<Database['public']['Tables']['generated_letters']['Insert']>;
      };
      payment_transactions: {
        Row: {
          id: string;
          tenant_id: string;
          client_id: string;
          fee_calculation_id: string | null;
          cardcom_deal_id: string | null;
          cardcom_transaction_id: string | null;
          amount: number;
          currency: string;
          status: PaymentStatus;
          payment_method: string | null;
          payment_link: string | null;
          invoice_number: string | null;
          payment_date: string | null;
          failure_reason: string | null;
          metadata: Record<string, unknown>;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['payment_transactions']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['payment_transactions']['Insert']>;
      };
      audit_logs: {
        Row: {
          id: string;
          tenant_id: string;
          user_id: string | null;
          user_email: string | null;
          action: string;
          module: string;
          resource_type: string | null;
          resource_id: string | null;
          details: Record<string, unknown>;
          ip_address: string | null;
          user_agent: string | null;
          timestamp: string;
        };
        Insert: Omit<Database['public']['Tables']['audit_logs']['Row'], 'id' | 'timestamp'>;
        Update: Partial<Database['public']['Tables']['audit_logs']['Insert']>;
      };
    };
    Views: Record<string, never>;
    Functions: {
      validate_israeli_tax_id: {
        Args: { tax_id: string };
        Returns: boolean;
      };
      format_ils: {
        Args: { amount: number };
        Returns: string;
      };
      format_israeli_date: {
        Args: { date_input: string };
        Returns: string;
      };
    };
    Enums: Record<string, never>;
  };
}