/**
 * Image Utilities for PDF Generation
 * Handles embedding images as base64 and removing links from HTML
 */

const imageCache = new Map<string, string>();

/**
 * Embed all external images as base64 data URIs in HTML
 * This ensures images appear in PDFs generated by Browserless
 */
export async function embedImagesAsBase64(html: string): Promise<string> {
  // All brand image URLs used in letter templates
  const imageUrls = [
    'https://ticovision.vercel.app/brand/Tico_logo_png_new.png',
    'https://ticovision.vercel.app/brand/tico_logo_240.png',
    'https://ticovision.vercel.app/brand/Tico_franco_co.png',
    'https://ticovision.vercel.app/brand/franco-logo-hires.png',
    'https://ticovision.vercel.app/brand/tagline.png',
    'https://ticovision.vercel.app/brand/bullet-star.png',
    'https://ticovision.vercel.app/brand/Bullet_star_blue.png',
  ];

  let modifiedHtml = html;

  // Replace each image URL with its base64 data URI
  for (const url of imageUrls) {
    const base64Url = await getBase64Image(url);
    // Use global regex to replace all occurrences
    modifiedHtml = modifiedHtml.replace(new RegExp(escapeRegExp(url), 'g'), base64Url);
  }

  return modifiedHtml;
}

/**
 * Fetch an image and convert it to base64 data URI
 * Results are cached to avoid repeated fetches
 */
async function getBase64Image(url: string): Promise<string> {
  // Check cache first
  if (imageCache.has(url)) {
    return imageCache.get(url)!;
  }

  // Fetch image
  const response = await fetch(url);
  if (!response.ok) {
    console.warn(`Failed to fetch image: ${url} (${response.status})`);
    return url; // Fallback to original URL
  }

  const buffer = await response.arrayBuffer();

  // Convert to base64
  const base64 = btoa(String.fromCharCode(...new Uint8Array(buffer)));
  const contentType = response.headers.get('content-type') || 'image/png';
  const dataUri = `data:${contentType};base64,${base64}`;

  // Cache and return
  imageCache.set(url, dataUri);
  return dataUri;
}

/**
 * Remove all links from HTML, converting <a> tags to <span>
 * This prevents non-functional links in the PDF
 */
export function removeLinks(html: string): string {
  // Replace <a href="...">text</a> with <span>text</span>
  // Preserves any inline styles on the <a> tag
  return html.replace(/<a\s+([^>]*)>(.*?)<\/a>/gi, (match, attrs, content) => {
    // Extract style attribute if exists
    const styleMatch = attrs.match(/style="([^"]*)"/i);
    const style = styleMatch ? ` style="${styleMatch[1]}"` : '';
    return `<span${style}>${content}</span>`;
  });
}

/**
 * Escape special regex characters in a string
 */
function escapeRegExp(string: string): string {
  return string.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}
